### ISSUE TITLE
Create a Django project and main app

### ISSUE THREAD

**Issue by AdrianDAlessandro** [AdrianDAlessandro/rse-competencies-toolkit-webapp#7]
The repo requires the initial Django project setup. To close this issue, we require a basic Django project and Django app called `main` with no modifications.

Do this following the [guide in the Django docs](https://docs.djangoproject.com/en/5.1/intro/tutorial01/)

There are a couple of extra things to consider for this repo. Since this repo was built from this [python template](https://github.com/ImperialCollegeLondon/python-template), there is already an initial package structure. This means:
- The package directory should be deleted in favour of the Django directory that Django's `startapp` command creates.
- The pre-commit checks will fail (force the commit without changes first, and then make those tests pass)
- The tests will fail (delete the existing test)

The final result should be similar to [the first 4 commits in this PR](https://github.com/ImperialCollegeLondon/drunc_ui/pull/15/files/4d82c208c6c0fc1d6a5ae2029bfd4cf383ce3c44)

**Comment by barneydobson** [comment]
I will have a look!
