### ISSUE TITLE
Configure Django settings

### ISSUE THREAD

**Issue by AdrianDAlessandro** [AdrianDAlessandro/rse-competencies-toolkit-webapp#8]
The Django settings need to be configured for this web app. We should:
- Add the `main` app to `INSTALLED_APPS`
- Refactor the settings into two options, one for development and one for production
- Create the DB directory and adjusts settings accordingly
- Configure static file handling with Whitenoise

Follow [the first 4 commits in this PR](https://github.com/ImperialCollegeLondon/drunc_ui/pull/24/files/f678a41d045042ddf14113a4fd12edb8faf2e2e5) as a guide

**Comment by barneydobson** [comment]
I will have a look
